version: '3.8'

services:
  # REST API - Question Service
  question_service_api:
    container_name: question_service_api
    image: peerprep_question_service_api
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # local->container
      - ${EXPRESS_LOCAL_PORT}:${EXPRESS_DOCKER_PORT}
    depends_on:
      - question_service_db
    networks:
      - peerprep

  # Database - Mongo DB
  question_service_db:
    container_name: question_service_db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/data:/data/db
    networks:
      - peerprep

networks:
  peerprep:
    external: true
