apiVersion: v1
kind: Service
metadata:
  name: question-service-api-service
  namespace: peerprep
spec:
  selector:
    app: question-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
