version: '3.8'

services:
  # REST API - Question Service
  api:
    container_name: question-service-api
    image: question-service-api
    restart: always
    env_file:
      - .env
    build: .
    ports:
      # local->container
      - 9001:9001
    depends_on: 
      - mongo
  # Database - Mongo DB
  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ../mongodb/docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../mongodb/data:/data/db